# Generated by Django 4.2.14 on 2024-07-13 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Иванов Иван', max_length=100, verbose_name='ФИО')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('images', models.ImageField(default='default.jpg', upload_to='user_images', verbose_name='Фото профиля')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата вступление на работу')),
                ('account_type', models.CharField(choices=[('Employee', 'Сотрудник'), ('Senior', 'Старший сотрудник'), ('Master', 'Мастер'), ('Director', 'Директор'), ('Admin', 'Администратор')], default='Employee', max_length=20, verbose_name='Должность')),
                ('filial', models.CharField(choices=[('Moscow', 'Москва'), ('Smolensk', 'Смоленск'), ('Petersburg', 'Санкт-Петербург'), ('Novgorod', 'Нижний Новгород'), ('Kaliningrad', 'Калининград')], default='Moscow', max_length=20, verbose_name='Филиал')),
                ('department', models.CharField(choices=[('Designer', 'Дизайнер'), ('Backend', 'Серевная'), ('Developers', 'Разработчики'), ('Researchers', 'Исследователи')], default='Developers', max_length=20, verbose_name='Отделение')),
                ('salary', models.IntegerField(default=50000, verbose_name='Оклад')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
