# Generated by Django 4.2.14 on 2024-07-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, default='123', max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
